### ISSUE TITLE
papierzak.exe

### ISSUE THREAD

**Issue by bartekpacia** [KacperFiga/backendJsLearning#1]
https://github.com/KacperFiga/backendJsLearning/blob/main/index.js#L6

<img width="524" alt="Screenshot 2022-10-09 at 11 25 30 AM" src="https://user-images.githubusercontent.com/40357511/194748931-dafcc754-7f5f-4f63-ab88-d179be7e2052.png">

**Comment by KacperFiga** [comment]
Przepiękny, można mergować
